export const PAGE_HOME = "PAGE_HOME";
export const PAGE_ONBOARDING = "PAGE_ONBOARDING";
export const PAGE_DESTINATION_LIST = "PAGE_DESTINATION_LIST";
export const PAGE_DESTINATION_DETAIL = "PAGE_DESTINATION_DETAIL";
export const PAGE_PROFIL = "PAGE_PROFIL";
export const PAGE_NAVBAR = "PAGE_NAVBAR";
export const PAGE_CHOOSE_TYPES = "PAGE_CHOOSE_TYPES";